services:
  - type: worker
    name: xauron-ai-telegram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DEFAULT_LANG
        value: PT
